// cloudflare-env.d.ts
// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
    // Square Integration Environment Variables
    SQUARE_APPLICATION_ID: string;
    SQUARE_ACCESS_TOKEN: string;
    SQUARE_ENVIRONMENT: "sandbox" | "production";
    SQUARE_LOCATION_ID: string;
    
    // Your existing Supabase environment variables (if any)
    NEXT_PUBLIC_SUPABASE_URL: string;
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
  }